name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch main)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch main

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        with:
          install_local_path_provisioner: false
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --target-branch main
          
      - name: Release Charts
        run: |
          changed=$(ct list-changed --target-branch main)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
        env:
           CHANGED: "${{ steps.list-changed.outputs.changed }}"

      - name: Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.1.0
        with:
          charts_repo_url: https://chrispyduck.github.io/charts
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
          GIT_AUTHOR_NAME: "GitHub Action"
          GIT_AUTHOR_EMAIL: "no@ema.il"
          GIT_COMMITTER_NAME: "GitHub Action"
          GIT_COMMITTER_EMAIL: "no@ema.il"
